### ISSUE TITLE
1.0.7 添加【虎皮椒】支付，填写完信息后支付提示 请求失败

### ISSUE THREAD

**Issue by ningguotong** [lizhipay/acg-faka#43]
集成了个人支付宝
1：输入了appid 和 密钥  通过虎皮椒后台获取
2：点击了保存

然后测试 支付 提示：请求失败

我在wp上面是还需要输入一个回调地址的，但是我不知道这个回调地址在哪里填写是否因为这个原因导致的

不知道怎么解决，希望得到大家帮助解决

**Comment by 928882650** [comment]
驱动是虎皮椒提供的嘛
