### ISSUE TITLE
测试邮件发送失败

### ISSUE THREAD

**Issue by XingHaiOvO** [lizhipay/acg-faka#68]
![1](https://github.com/lizhipay/acg-faka/assets/110782064/23bb8e05-2c96-48af-a438-766588d6d4aa)

**Comment by Markli66** [comment]
请问解决了吗？是设置的问题吗？

**Comment by XingHaiOvO** [comment]
> 请问解决了吗？是设置的问题吗？

解决了我的问题

**Comment by dadatom** [comment]
> > 请问解决了吗？是设置的问题吗？
> 
> 解决了我的问题

请问是什么问题，我也遇到了

**Comment by Markli66** [comment]
我是用163邮箱发送了，QQ邮箱的465端口不知道是什么原因，即使是在安全组和面板里放开了465端口依然是发送失败，开放了163邮箱的994还是993端口后在安全组和防火墙同时开放就行，163邮箱开开STMP功能就行。顺便吐槽一下10U 10RMB解决问题的蛮多哈哈哈哈

**Comment by dadatom** [comment]
> 我是用163邮箱发送了，QQ邮箱的465端口不知道是什么原因，即使是在安全组和面板里放开了465端口依然是发送失败，开放了163邮箱的994还是993端口后在安全组和防火墙同时开放就行，163邮箱开开STMP功能就行。顺便吐槽一下10U 10RMB解决问题的蛮多哈哈哈哈

我使用的是 Lark 的自定义域名邮箱，各项功能都已经开启，但是始终无法发送

**Comment by dadatom** [comment]
> 我是用163邮箱发送了，QQ邮箱的465端口不知道是什么原因，即使是在安全组和面板里放开了465端口依然是发送失败，开放了163邮箱的994还是993端口后在安全组和防火墙同时开放就行，163邮箱开开STMP功能就行。顺便吐槽一下10U 10RMB解决问题的蛮多哈哈哈哈

是需要为服务器开启端口吗？我是把服务部署在家里的树莓派上

**Comment by Markli66** [comment]
> > 我是用163邮箱发送了，QQ邮箱的465端口不知道是什么原因，即使是在安全组和面板里放开了465端口依然是发送失败，开放了163邮箱的994还是993端口后在安全组和防火墙同时开放就行，163邮箱开开STMP功能就行。顺便吐槽一下10U 10RMB解决问题的蛮多哈哈哈哈
> 
> 是需要为服务器开启端口吗？我是把服务部署在家里的树莓派上

树莓派倒是不清楚，我的是CentoOS系统的的云服务器

**Comment by qinfeng0214** [comment]
> > 请问解决了吗？是设置的问题吗？
> 
> 解决了我的问题

请问qq邮箱是如何解决的，是不是端口不是465？
