### ISSUE TITLE
此项目现状和一些想法 随便聊聊

### ISSUE THREAD

**Issue by Qlmuby** [lizhipay/acg-faka#77]
企业版是在线授权，和机器IP绑定（解绑或者换服务器搭建要联系作者），加上现在作者消失很久了，没人处理售后问题，企业版现在买了基本就是打水漂，想换服务器想解绑的，运气好也做好等至少一个星期的准备，要买的话建议先多聊几次试探试探，看看有几次理你再决定，授权服务器每隔一段时间发请求验证，不是国内的备案机器的比如国外服务器线路稍差一点点，所有收费插件就会经常全部掉线停止运行，非常烦人，就作者现状来看不要对后续维护做什么期待比较好，要是能有大佬能接手这项目最好了，二次元发卡功能全面还有开发者插件市场的项目，市面上貌似就这一个，没有第二家，奈何作者后继乏力，不介意付费但最好对付费用户负责些。

**Comment by wngx99** [comment]
有什么替代产品吗？

**Comment by Qlmuby** [comment]
> 有什么替代产品吗？

我也想知道，可惜没找到

**Comment by xshwy** [comment]
我今天也遇到 **所有插件被自动停**用 的问题了，导致线上出现问题长达2天才发现…
